# Generated by Django 6.0.3 on 2026-05-10 19:50

import authentification.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='cpf',
            field=authentification.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=authentification.fields.EncryptedCharField(blank=True),
        ),
    ]
