# Generated by Django 6.0.3 on 2026-05-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(choices=[(1, '1º slide'), (2, '2º slide'), (3, '3º slide')], unique=True, verbose_name='Posição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('image_desktop', models.ImageField(blank=True, help_text='Tamanho recomendado: 1440 × 400 px (proporção 16:4)', null=True, upload_to='carousel/desktop/', verbose_name='Imagem desktop')),
                ('image_mobile', models.ImageField(blank=True, help_text='Tamanho recomendado: 640 × 400 px (proporção 8:5)', null=True, upload_to='carousel/mobile/', verbose_name='Imagem mobile')),
                ('is_launch', models.BooleanField(default=False, verbose_name='Marcador Lançamento')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Marcador Promoção')),
                ('title', models.CharField(blank=True, help_text='Texto grande. Aceita markdown: **negrito**, *itálico*', max_length=200, verbose_name='Título')),
                ('subtitle', models.TextField(blank=True, help_text='Texto abaixo do título. Aceita markdown: **negrito**, *itálico*', verbose_name='Subtítulo')),
                ('text_alignment', models.CharField(choices=[('left', 'Esquerda'), ('center', 'Centro'), ('right', 'Direita')], default='left', max_length=10, verbose_name='Posição do texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slide do Carrossel',
                'verbose_name_plural': 'Slides do Carrossel',
                'ordering': ['order'],
            },
        ),
    ]
