# Generated by Django 6.0.3 on 2026-05-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinstrument',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
