# Generated by Django 6.0.3 on 2026-05-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_complement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='shipping_street',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_complement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_neighborhood',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_street',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
